PAGES = [
dict(slug='broken-bones', title='Broken Bones', hero='BROKEN BONES', img='hero-broken-bones',
 meta_title='Bone Broken Treatment & Emergency Fracture Care',
 meta_desc='Looking for a doctor of broken bones? East Houston Medical Center provides prompt evaluation and emergency care for fractures and other bone injuries.',
 sym_title='Symptoms of <span>Broken Bones</span>',
 sym_intro='Broken bones can cause different symptoms depending on the injury. Recognizing common signs can help you know when medical evaluation may be needed.',
 symptoms=[('Severe Pain','Sudden or intense pain around the injured area, especially with movement or pressure.'),
  ('Swelling & Bruising','Swelling, bruising, or tenderness around the injured bone after trauma or impact.'),
  ('Deformity','An unusual bend, shape, or position of the injured area may indicate a fracture.'),
  ('Limited Movement','Difficulty moving the affected arm, leg, joint, or other injured area normally.'),
  ('Tenderness','Pain or tenderness when touching or putting pressure on the injured area.'),
  ('Numbness or Tingling','Numbness, tingling, or weakness near the injury may require prompt medical evaluation.'),
  ('Visible Bone','Bone breaking through the skin requires immediate emergency evaluation and care.'),
  ('Difficulty Bearing Weight','Pain or weakness that makes it difficult to stand, walk, or use the injured limb.')],
 help_intro='When you need medical attention for a broken bone, our emergency team is ready to assess your injury, provide treatment, and guide the next steps in your care.',
 help=[('Rapid Triage & Diagnosis','We quickly evaluate your injury and determine the appropriate level of care, helping you receive treatment without unnecessary delays.'),
  ('On-Site Imaging & Labs','Access essential diagnostic testing in the ER to help identify fractures and guide appropriate treatment decisions.'),
  ('Splinting & Pain Management','Our team provides appropriate care to stabilize the injury, reduce pain, and protect the affected area.'),
  ('Specialist Coordination','When your fracture requires additional care, our doctor of broken bones can coordinate with specialists and providers to help ensure a smooth transition.')],
 faq_intro='Get answers about broken bones, emergency symptoms, testing, and fracture care.',
 faq=[('When should I go to the ER for a broken bone?','Seek emergency care for severe pain, visible deformity, an open fracture, numbness, heavy bleeding, or difficulty moving the injured area.'),
  ('What can cause a broken bone?','Broken bones can result from falls, sports injuries, accidents, direct impacts, or weakened bones. Medical evaluation can confirm the injury.'),
  ('How are broken bones diagnosed in the ER?','The ER team reviews your injury and medical history and may use an exam and X-rays or other imaging to identify the fracture.'),
  ('Can I get urgent care for a fracture?','Urgent care for fracture injuries may be appropriate for some stable fractures, while severe or complicated injuries require emergency evaluation.'),
  ('Should I wait if I think I broke a bone?','Do not delay medical care if pain is severe, the bone looks deformed, or you have numbness, heavy bleeding, or an open wound.')]),
dict(slug='high-fever', title='High Fever', hero='HIGH FEVER', img='hero-high-fever',
 meta_title='High Fever Urgent Care & Emergency Evaluation',
 meta_desc='Need high fever treatment? East Houston Medical Center provides prompt evaluation and emergency care for persistent or concerning fever symptoms.',
 sym_title='Symptoms of <span>High Fever</span>',
 sym_intro='High fever can cause different symptoms depending on its cause. Recognizing common signs can help you know when to go to er for high fever.',
 symptoms=[('High Temperature','A body temperature that is unusually high and may persist despite rest, fluids, or home care.'),
  ('Chills & Sweating','Chills, shivering, or heavy sweating may occur as your body responds to a fever.'),
  ('Headache','A headache may occur with fever, especially when the temperature remains elevated.'),
  ('Body Aches','Muscle aches, weakness, or general discomfort can occur alongside a high fever.'),
  ('Dehydration','Dry mouth, thirst, reduced urination, or dizziness may indicate dehydration with fever.'),
  ('Confusion or Weakness','Confusion, unusual drowsiness, severe weakness, or difficulty staying alert requires prompt evaluation.'),
  ('Breathing Problems','Difficulty breathing, chest discomfort, or rapid breathing with a high fever requires immediate care.'),
  ('Persistent Fever','A high fever for 24 hours or longer may require medical evaluation, especially with worsening symptoms.')],
 help_intro='When you need medical attention for a high fever, our emergency team is ready to assess your condition, provide treatment, and guide the next steps in your care.',
 help=[('Rapid Triage & Diagnosis','We quickly evaluate your symptoms and determine the appropriate level of care, helping you receive treatment without unnecessary delays.'),
  ('On-Site Imaging & Labs','Access essential diagnostic testing in the ER to help identify the cause of your fever and guide treatment decisions.'),
  ('Fluids & Fever Management','Our team provides appropriate treatment for high fever to manage symptoms, support hydration, and stabilize your condition.'),
  ('Specialist Coordination','When your fever requires additional care, we coordinate with specialists and providers to help ensure a smooth transition.')],
 faq_intro='Get answers about high fever, emergency symptoms, testing, and fever care.',
 faq=[('When should I go to the ER for high fever?','Seek emergency care if fever is severe or accompanied by confusion, difficulty breathing, severe weakness, dehydration, or other serious symptoms.'),
  ('What can cause a high fever?','High fever can result from infections and other medical conditions. Medical evaluation can help identify the underlying cause when symptoms are severe or persistent.'),
  ('When should I seek urgent care for high fever?','High fever urgent care may be appropriate when fever needs prompt evaluation but there are no signs of a life-threatening emergency.'),
  ('How is high fever diagnosed in the ER?','The ER team reviews your symptoms and medical history and may perform an exam or tests to identify the cause of the fever.'),
  ('Where can I get high fever treatment in Houston?','For high fever treatment Houston TX, prompt medical evaluation can help determine the cause and appropriate treatment, especially when symptoms are worsening.')]),
dict(slug='severe-bleeding', title='Severe Bleeding', hero='SEVERE BLEEDING', img='hero-severe-bleeding',
 meta_title='Treatment of Severe Bleeding & Emergency Care',
 meta_desc='A bleeding injury may require immediate medical attention. East Houston Medical Center provides prompt evaluation and emergency care for severe bleeding.',
 sym_title='Symptoms of <span>Severe Bleeding</span>',
 sym_intro='Severe bleeding can vary depending on its source and severity. Recognizing clinical signs of bleeding can help you know when medical care is needed.',
 symptoms=[('Heavy Blood Loss','Bleeding that is heavy, continuous, or difficult to control requires prompt medical care.'),
  ('Dizziness or Weakness','Feeling dizzy, weak, or lightheaded may occur with significant blood loss.'),
  ('Pale or Clammy Skin','Pale, cool, or clammy skin can occur when the body responds to blood loss.'),
  ('Rapid Heartbeat','A fast heartbeat may occur as the body responds to significant blood loss.'),
  ('Confusion or Fainting','Confusion, unusual drowsiness, or fainting may indicate severe blood loss.'),
  ('Blood in Vomit or Stool','Blood in vomit or stool can indicate internal bleeding and requires prompt care.'),
  ('Severe Nose Bleeds','Severe nose bleeds that do not stop with direct pressure require prompt evaluation.'),
  ('Signs of Internal Bleeding','Severe pain, weakness, or fainting may be signs of internal bleeding requiring immediate care.')],
 help_intro='When you need medical attention for severe bleeding, our emergency team is ready to assess your condition, provide treatment, and guide the next steps in your care.',
 help=[('Rapid Triage & Diagnosis','We quickly assess your bleeding and determine the right level of care, helping you receive treatment without unnecessary delays.'),
  ('On-Site Imaging & Labs','Access essential diagnostic testing in the ER to help identify the source of bleeding and guide treatment decisions.'),
  ('Bleeding Control & Stabilization','Our team provides appropriate care to control blood loss, support circulation, and stabilize your condition.'),
  ('Specialist Coordination','When bleeding requires additional care, we coordinate with specialists and providers to help ensure a smooth transition.')],
 faq_intro='Get answers about severe bleeding, warning signs, testing, and emergency care.',
 faq=[('When should I go to the ER for severe bleeding?','Seek emergency care when bleeding is heavy, does not stop with pressure, or is accompanied by dizziness, weakness, or fainting.'),
  ('What are the different types of bleeding?','The main types of bleeding include bleeding from arteries, veins, and smaller blood vessels. The source and severity determine the needed care.'),
  ('What are signs of internal bleeding?','Common signs of internal bleeding may include severe pain, weakness, dizziness, fainting, or blood in vomit or stool.'),
  ('What should I do for severe bleeding?','Apply firm pressure to an external wound and seek emergency care for uncontrolled bleeding or significant blood loss.'),
  ('What is first aid for bleeding?','Basic first aid for bleeding includes applying firm pressure with clean cloth or gauze until the bleeding stops or help arrives.')]),
dict(slug='difficulty-breathing', title='Difficulty Breathing', hero='DIFFICULTY BREATHING', img='hero-difficulty-breathing',
 meta_title='Respiratory Conditions & Emergency Breathing Care',
 meta_desc='Need an ER for respiratory conditions? East Houston Medical Center provides prompt evaluation and emergency care for breathing difficulties and respiratory distress.',
 sym_title='Symptoms of <span>Respiratory Distress</span>',
 sym_intro='Difficulty breathing can have different causes and may become serious quickly. Recognizing signs of respiratory distress can help you know when emergency care is needed.',
 symptoms=[('Shortness of Breath','Feeling unable to get enough air or having difficulty breathing normally, even at rest.'),
  ('Rapid Breathing','Breathing faster than usual may occur when the body is struggling to get enough oxygen.'),
  ('Chest Tightness','Pressure or tightness in the chest may occur with breathing problems or airway irritation.'),
  ('Wheezing','A high-pitched or whistling sound when breathing may indicate narrowed airways or other problems.'),
  ('Blue or Pale Skin','Bluish or unusually pale lips, face, or fingertips may indicate low oxygen levels.'),
  ('Confusion or Dizziness','Confusion, dizziness, or unusual drowsiness may occur when breathing problems affect oxygen levels.'),
  ('Difficulty Speaking','Severe breathing problems may make it difficult to speak in full sentences without stopping.'),
  ('Severe Breathing Difficulty','Sudden or worsening difficulty breathing requires immediate medical evaluation and care.')],
 help_intro='When you need medical attention for breathing problems, our emergency team is ready to assess your condition, provide treatment, and guide the next steps in your care.',
 help=[('Rapid Triage & Diagnosis','We quickly evaluate your breathing and determine the right level of care, helping you receive treatment without unnecessary delays.'),
  ('On-Site Imaging & Labs','Access essential diagnostic testing in the ER to help identify the cause of breathing problems and guide treatment decisions.'),
  ('Oxygen & Breathing Support','Our team provides appropriate care to support breathing, improve oxygen levels, and stabilize your condition.'),
  ('Specialist Coordination','When breathing problems require additional care, we coordinate with specialists and providers to help ensure a smooth transition.')],
 faq_intro='Get answers about breathing problems, emergency symptoms, testing, and respiratory care.',
 faq=[('What can cause difficulty breathing?','Common causes include asthma, respiratory infections, heart conditions, allergies, and other lung or medical conditions.'),
  ('How is respiratory distress diagnosed in the ER?','The ER team reviews your symptoms and medical history and may use an exam, oxygen measurement, imaging, or other tests.'),
  ('When should I go to the ER for respiratory distress?','Go to the ER for Respiratory Distress when breathing problems are sudden, severe, or require immediate medical evaluation.'),
  ('When should I see a shortness of breath doctor?','A shortness of breath doctor can evaluate recurring or unexplained breathing problems. Severe or sudden symptoms require emergency medical care.'),
  ('Should I wait if I am having difficulty breathing?','Do not wait if breathing difficulty is sudden, severe, or worsening. Immediate emergency evaluation may be needed.')]),
dict(slug='allergic-reactions', title='Allergic Reactions', hero='ALLERGIC REACTIONS', img='hero-allergic-reactions',
 meta_title='ER for Allergic Reaction & Emergency Allergy Care',
 meta_desc='Looking for allergy treatment near me? East Houston Medical Center offers prompt care for allergic reactions and severe allergy symptoms.',
 sym_title='Symptoms of <span>Allergic Reactions</span>',
 sym_intro='Allergic reactions can cause different symptoms depending on the trigger and severity. Recognizing common allergy symptoms can help you know when medical care is needed.',
 symptoms=[('Skin Rash','Redness, itching, or a raised rash may develop after exposure to an allergen.'),
  ('Hives','Raised, itchy welts can appear suddenly on the skin and may spread quickly.'),
  ('Swelling','Swelling of the lips, face, tongue, or throat may require immediate medical attention.'),
  ('Itchy or Watery Eyes','Itchy, red, or watery eyes may occur with allergies, especially after exposure to triggers.'),
  ('Sneezing & Congestion','Sneezing, a runny nose, or nasal congestion may occur with an allergic reaction.'),
  ('Coughing or Wheezing','Coughing, wheezing, or difficulty breathing can indicate a serious allergic reaction.'),
  ('Nausea or Vomiting','Nausea, vomiting, or stomach discomfort may occur with certain allergic reactions.'),
  ('Severe Reaction','Sudden breathing difficulty, throat swelling, dizziness, or fainting requires immediate emergency care.')],
 help_intro='When you need medical attention for an allergic reaction, our emergency team is ready to assess your condition, provide treatment, and guide the next steps in your care.',
 help=[('Rapid Triage & Diagnosis','We quickly evaluate your symptoms and determine the right level of care, helping you receive treatment without unnecessary delays.'),
  ('On-Site Imaging & Labs','Access essential diagnostic testing in the ER to help evaluate your condition and guide appropriate treatment decisions.'),
  ('Allergy Treatment & Monitoring','Our team provides appropriate allergy treatment to manage symptoms, reduce risks, and stabilize your condition.'),
  ('Specialist Coordination','When your reaction requires additional care, we coordinate with specialists and providers to help ensure a smooth transition.')],
 faq_intro='Get answers about allergic reactions, symptoms, emergency care, testing, and treatment.',
 faq=[('When should I go to the ER for an allergic reaction?','Go to the ER for allergic reaction symptoms when there is difficulty breathing, throat swelling, severe dizziness, fainting, or rapidly worsening symptoms.'),
  ('What can cause a severe allergic reaction?','Severe reactions can be triggered by foods, medications, insect stings, latex, or other allergens. Symptoms may develop quickly and require emergency care.'),
  ('How are allergic reactions diagnosed in the ER?','The ER team reviews your symptoms, medical history, and possible allergen exposure. A physical exam helps determine the severity and treatment.'),
  ("Can I come to the ER if I don't know what is causing my allergic reaction?",'Yes. You can visit the ER for an unexplained reaction, especially if symptoms are severe, worsening, or affecting your breathing.'),
  ('Should I wait to see if a severe allergic reaction goes away?','No. Seek emergency care if you have breathing difficulty, throat swelling, dizziness, fainting, or rapidly worsening symptoms.')]),
dict(slug='blood-clots', title='Blood Clots', hero='BLOOD CLOT', img='hero-blood-clots',
 meta_title='Blood Clot Treatment & Emergency Care',
 meta_desc='Need a blood clot doctor? East Houston Medical Center provides prompt evaluation and emergency care for suspected blood clots and related symptoms.',
 sym_title='Symptoms of a <span>Blood Clot</span>',
 sym_intro='Blood clots can cause different symptoms depending on where they develop. Recognizing common blood clot symptoms can help you know when medical care is needed.',
 symptoms=[('Leg Swelling','Swelling in one leg, especially around the calf or thigh, may indicate a blood clot.'),
  ('Leg Pain','Pain, tenderness, or cramping in one leg may occur with a blood clot.'),
  ('Skin Changes','Redness, warmth, or discoloration over an affected area may occur with a clot.'),
  ('Chest Pain','Sudden chest pain or pressure may occur when a clot travels to the lungs.'),
  ('Shortness of Breath','Sudden difficulty breathing may indicate a serious clot affecting the lungs.'),
  ('Rapid Heartbeat','A fast or irregular heartbeat may occur with a blood clot in the lungs.'),
  ('Coughing Blood','Coughing up blood can be a warning sign of a serious clot and requires immediate care.'),
  ('Sudden Weakness','Sudden weakness, confusion, or difficulty speaking may indicate a clot affecting the brain.')],
 help_intro='When you need medical attention for a blood clot, our emergency team is ready to assess your condition, provide treatment, and guide the next steps in your care.',
 help=[('Rapid Triage & Diagnosis','We quickly evaluate your symptoms and determine the right level of care, helping you receive treatment without unnecessary delays.'),
  ('On-Site Imaging & Labs','Access essential diagnostic testing in the ER to help identify a clot and guide appropriate treatment decisions.'),
  ('Blood Clot Treatment',"Our team provides appropriate blood clot treatment based on the clot's location, severity, and potential complications."),
  ('Specialist Coordination','When your condition requires additional care, we coordinate with specialists and providers to help ensure a smooth transition.')],
 faq_intro='Get answers about blood clots, warning signs, testing, and emergency care.',
 faq=[('When should I go to the ER for a blood clot?','Seek ER for Blood clot care for sudden chest pain, difficulty breathing, coughing blood, fainting, or other severe symptoms.'),
  ('What can cause a blood clot?','Blood clots may develop from prolonged immobility, surgery, injury, certain medications, or underlying medical conditions.'),
  ('What are blood clotting disorders?','Blood clotting disorders can cause blood to clot too easily or prevent normal clotting. Medical evaluation can help identify these conditions.'),
  ('Can I go to urgent care for a blood clot?','Urgent care for blood clot concerns may be appropriate for evaluation, but severe symptoms require immediate emergency care.'),
  ('Should I wait if I think I have a blood clot?','Do not delay care if you have sudden chest pain, shortness of breath, coughing blood, or severe swelling or pain.')]),
dict(slug='infection', title='Infection', hero='INFECTION', img='hero-infection',
 meta_title='Treatment for Infection & Emergency Care',
 meta_desc='Need treatment for infection types? East Houston Medical Center provides prompt evaluation and treatment for a wide range of infections and related symptoms.',
 sym_title='Symptoms of <span>Infection</span>',
 sym_intro='Infections can affect different parts of the body and may vary in severity. Recognizing common Infection signs can help you know when medical evaluation is needed.',
 symptoms=[('Fever & Chills','Fever, chills, or sweating may occur as the body responds to an infection.'),
  ('Fatigue or Weakness','Feeling unusually tired or weak may occur while your body fights an infection.'),
  ('Pain or Swelling','Pain, tenderness, redness, or swelling may develop around the affected area.'),
  ('Cough or Congestion','Coughing, congestion, or throat irritation may occur with respiratory infections.'),
  ('Nausea & Vomiting','Nausea, vomiting, or stomach discomfort may occur with certain infections.'),
  ('Skin Changes','Redness, warmth, swelling, or drainage may indicate an infection affecting the skin.'),
  ('Changes in Urination','Painful urination, frequent urination, or unusual urine changes may occur with some infections.'),
  ('Severe Symptoms','Severe weakness, confusion, difficulty breathing, or worsening symptoms require prompt medical care.')],
 help_intro='When you need medical attention for an infection, our emergency team is ready to assess your condition, provide treatment, and guide the next steps in your care.',
 help=[('Rapid Triage & Diagnosis','We quickly evaluate your symptoms and determine the right level of care, helping you receive treatment without unnecessary delays.'),
  ('On-Site Imaging & Labs','Access essential diagnostic testing in the ER to help identify the infection and guide treatment decisions.'),
  ('Infection Treatment & Monitoring',"Our team provides appropriate care based on the infection's type, location, and severity."),
  ('Specialist Coordination','When your infection requires additional care, we coordinate with specialists and providers to help ensure a smooth transition.')],
 faq_intro='Get answers about infections, testing, emergency symptoms, and treatment.',
 faq=[('What are the different types of infections?','Common infection types include bacterial, viral, fungal, and parasitic infections. Treatment depends on the type and location of the infection.'),
  ('What are infections caused by?','Infections are caused by microorganisms such as bacteria, viruses, fungi, or parasites that enter and multiply in the body.'),
  ('What is a viral infection?','A viral infection occurs when a virus enters the body and multiplies within its cells. Some viral infections resolve with supportive care, while others may require medical evaluation.'),
  ('When should I go to the ER for an infection?','Seek ER for infections when symptoms are severe, rapidly worsening, or accompanied by confusion, difficulty breathing, or other concerning signs.'),
  ('Can I go to urgent care for an infection?','Urgent care for infections may be appropriate for mild or moderate symptoms that need prompt attention but are not life-threatening.')]),
dict(slug='diabetic-emergency', title='Diabetic Emergency', hero='DIABETIC EMERGENCY', img='hero-diabetic-emergency',
 meta_title='ER for Diabetic Emergency & Urgent Diabetes Care',
 meta_desc='Looking for diabetes treatment near me? East Houston Medical Center provides prompt emergency care for diabetic emergencies and related complications.',
 sym_title='Symptoms of a <span>Diabetic Emergency</span>',
 sym_intro='A diabetic emergency can cause different symptoms depending on blood sugar levels. Recognizing signs can help you know when immediate medical care is needed.',
 symptoms=[('Shaking or Sweating','Shaking, sweating, or feeling unusually nervous may occur when blood sugar drops too low.'),
  ('Dizziness or Weakness','Feeling dizzy, weak, or lightheaded may occur with dangerously low blood sugar.'),
  ('Confusion','Confusion, difficulty concentrating, or unusual behavior may occur during a diabetic emergency.'),
  ('Extreme Thirst','Excessive thirst and frequent urination may occur when blood sugar levels become too high.'),
  ('Nausea & Vomiting','Nausea, vomiting, or stomach pain may occur with dangerously high blood sugar.'),
  ('Rapid Breathing','Fast or deep breathing can occur when high blood sugar causes serious metabolic changes.'),
  ('Loss of Consciousness','Fainting or loss of consciousness may indicate a severe diabetic emergency requiring immediate care.'),
  ('Severe Symptoms','Severe confusion, difficulty breathing, or unconsciousness requires immediate emergency medical attention.')],
 help_intro='When you need medical attention for a diabetic emergency, our emergency team is ready to assess your condition, provide treatment, and guide the next steps in your care.',
 help=[('Rapid Triage & Diagnosis','We quickly evaluate your symptoms and blood sugar levels, helping determine the right level of care without unnecessary delays.'),
  ('On-Site Imaging & Labs','Access essential diagnostic testing in the ER to help identify complications and guide appropriate treatment decisions.'),
  ('Blood Sugar Management','Our team provides appropriate diabetic emergency care to stabilize blood sugar levels and manage related complications.'),
  ('Specialist Coordination','When your condition requires additional care, we coordinate with specialists and providers to help ensure a smooth transition.')],
 faq_intro='Get answers about diabetic emergencies, warning signs, testing, and emergency care.',
 faq=[('What can cause a diabetic emergency?','A diabetic emergency may result from blood sugar that becomes too high or too low. Illness, missed medication, dehydration, or other factors may contribute.'),
  ('How is a diabetic emergency diagnosed in the ER?','The ER team checks blood sugar and reviews your symptoms and medical history. Additional laboratory tests may help identify related complications.'),
  ('When should I seek diabetic urgent care?','Diabetic urgent care may be appropriate for concerning symptoms that need prompt evaluation but are not life-threatening. Severe symptoms require emergency care.'),
  ('When should I go to the emergency room for a diabetic emergency?','Visit the emergency room for severe confusion, loss of consciousness, difficulty breathing, or other signs of a serious diabetic complication.'),
  ('Should I wait if I think I am having a diabetic emergency?','No. A suspected ER for diabetic emergency situation requires prompt medical evaluation, especially when symptoms are severe or worsening.')]),
]
